### ISSUE TITLE
License and package review request (Python)

### ISSUE THREAD

**Issue by lzung** [UBC-MDS/colourpycker#43]
Ensure that the following changes are complete:
- [x] Examine the license and decide whether it should be changed
- [x] Discuss reasons for the license choice in issues
- [x] Link to the R issue if the discussion is on that repository
- [x] Initiate a review request by opening an issue using the [template](https://github.com/pyOpenSci/software-review/issues/new/choose) (https://github.com/UBC-MDS/software-review-2023)

**Comment by shaunhutch** [comment]
Finished review request here: [Issue](https://github.com/UBC-MDS/software-review-2023/issues/27)

**Comment by shaunhutch** [comment]
At the moment, both of our packages are licensed under the MIT License. This license is one of the most common. It allows offers users the most flexibility with using our package.  The requirements of using our package are that they include both copyright and license notices.

In a review of other options, I discovered that some options are:
Use a community license
GNU GPLv3
Apache
The Unlicense

Since we are not working within a community, we do not need to continue with a community or project license. This would be if we had either created a request for a previous project or were extending this project. Or if we were extending an existing project that required us to use 

The GNU GPLv3 also is fairly open about what users can do with our package. Like the MIT License, they require both copyright and license notices. In addition to the MIT notice, the GPL requires users to use the same license. In addition, we would be required to grant patent rights. The Apache License works similarly to the GNU GPLv3 but also explicitly states that it does not permit trademark rights.

The Unlicense allows anyone to do anything with our project without restrictions on licenses or patent rights. 

I believe that the current MIT License is the correct License for this project. This seems like the most straightforward strategy and allows for the most open-source collaboration with still including our copyright and license notices. The packages that we used in our package creation like Pillow used HPND License or their own licenses. So, I do not believe that we need to follow their licenses.

Sources:
https://choosealicense.com/

**Comment by ataciuk** [comment]
Thanks for doing that research, Shaun.  I agree that it makes sense to continue with the MIT license.

**Comment by lzung** [comment]
For the Python package, I think it makes sense to stick with the MIT License since our dependencies also use the same license. However for R, would it make more sense to adopt the GNU GPLv3 license? This would be because [`colorfindr`](https://github.com/zumbov2/colorfindr) uses the GPL license, which we have included in our package.

**Comment by rkrishnan-arjun** [comment]
I agree that our python package, colourpycker, should remain under the MIT License. This aligns with the license of our dependency, [extcolors](https://pypi.org/project/extcolors/), and allows for community benefits while protecting us from liability. 

Also, as the R package, [colorfindr,](https://cran.r-project.org/web/packages/colorfindr/colorfindr.pdf) uses GPL (>= 2), and since we [cannot convert it into MIT License or other license options](https://www.tawesoft.co.uk/kb/article/mit-license-faq#:~:text=No.,still%20contain%20MIT%2Dlicensed%20software.), we might as well use GPLv3 to align with the latest improvements in the license.

**Comment by lzung** [comment]
I have updated the R package to adopt the GPLv3 license and will leave the Python package license as is.
